### ISSUE TITLE
PyPI and Windows support

### ISSUE THREAD

**Issue by micahcochran** [mcvittal/qpy#1]
PyPI is a website that  makes it easy to install python modules with the command `$ (sudo) pip install qpy`.  Someone would need make a setup.py, but it makes installation a snap for end users.  You can check in the module if `import qgis` works.

[Qpy seems to already be a package on PyPi](https://pypi.python.org/pypi/qpy/) for XML parsing.  Perhaps a name change?

``` Python
sys.path.append('/usr/share/qgis/python/plugins')
```

For Windows using OSGeo4W--one of the recommended ways to installed QGIS on Windows--I commented that out and added this `sys.path.append(r'C:\OSGeo4W\apps\qgis\python\plugins')`.

It could be modified like this:

``` Python
import platform
if platform.system == 'Windows':
    sys.path.append(r'C:\OSGeo4W\apps\qgis\python\plugins')
else:
    sys.path.append('/usr/share/qgis/python/plugins')
```

There has to be a better way, but it would probably take a few more lines of code.

Note: I did get `import qpy` to work on OSGeo4W, but it took a few extra steps.  I'll do some testing to see what I can break.  :smiling_imp:

**Comment by micahcochran** [comment]
in processing_obj the class QProcess has a line `QgsApplication.setPrefixPath("/usr", True)`.  I set it to `QgsApplication.setPrefixPath(r'C:/OSGeo4W/apps/qgis', True)`.

I'm having problems with the qpy.alghelp() and qpy.alglist().  qpy.alghelp('qgis:clip') returns `Algorithm not found`.  qpy.alglist() returns nothing.  If I run these in QGIS's Python console, I get expect output.  I assume that something for processing is not be setup correctly.  I'm using QGIS 2.12.3-Lyon under Windows.

**Comment by mcvittal** [comment]
Yes, this issue of qpy.alglist() returning nothing popped up at some point between QGIS 12.1 and 12.3. I've been busy with school recently, but reading week is coming up in a week and a half so I should be able to dedicate some time to finding a fix. alglist always returns none, but issues a print statement so a properly functioning alglist method will return the same data type as the malfunctioning alglist method.

Haven't considered what to change the name to since qpy already exists in pypi, but that'll be something else to look into over the break.

**Comment by mcvittal** [comment]
Managed to fix the qpy.alglist() issue today at a LAN/coding party put on by a club at my university. Would you be able to see if it works on Windows? I only have Linux on my machine but I'll set up a virtualbox of windows 7 during reading week.

**Comment by micahcochran** [comment]
Thanks for getting on this so quickly!  I did a small amount of Windows testing.

`LD_LIBRARY_PATH` - doesn't seem to be needed for windows.

Here is what worked for me for processing_obj.py

``` Python
#!/usr/bin/python
# Prepare the environment
import sys, os
# Setup path to processing modules
qgisprefix = 'C:/OSGeo4W/apps/qgis'
sys.path.insert(0, qgisprefix+'/python/plugins')  # where processing/ folder is at
os.environ['QGIS_DEBUG'] = '-1'
#Package imports
[...snip..]
```

These environment variables before running Python, so they putting them in the processing_obj.py won't work--I tried.  So, I threw these in the C:\OSGeo4W\OSGeo4W.bat, which starts the OSGeo4W dos shell.  They could be set elsewhere that you setup environment variables.

```
set PYTHONPATH=%OSGEO4W_ROOT%\apps\qgis\python
set PATH=%OSGEO4W_ROOT%\apps\qgis\bin;%PATH%
```

In that batch file `OSGEO4W_ROOT` is set to `C:\OSGeo4W\`

After I do that qpy.alglist(), prints out a bunch of lines of algorithms, so that is working.

Curiously, I didn't even change the line `return qgis.core.QgsMapLayerRegistry.instance().mapLayers().values()`.

Thanks again.

**Comment by mcvittal** [comment]
Cool, thanks for the input! I'll be doing more rigorous testing in a Windows environment next week hopefully, and be able to get a nice V1.0 beta release up to PyPI sometime around then. 

What I'll most likely do for workflow will be to not include the "simple" methods (eg .clip, .erase, etc) and instead create some wrapper functions for the .runalg() functions, allowing you to pass in a path to the shapefile and then have the qpy modules generate the appropriate vector or raster object type. I can't see why that wouldn't be feasable, but it might be a bit more complex than what I'm anticipating.

Thanks again for the input!

**Comment by mcvittal** [comment]
After a long 8 months, this project now works on Windows in a standalone shell! It's a bit of a hack, since it's got a hardcoded path added using sys.path, so it currently only works if you have QGIS 2.14 installed under Program Files. I'll work on figuring out how to make Python figure out where QGIS is installed, or have it only officially supported if it's installed under C:\OSGeo4W. What are your thoughts?

**Comment by mcvittal** [comment]
I should also mention that the development work is done on the unstable branch. Really, both branches are unstable but once I get far enough to be satisfied, I'll merge unstable with master and create the PyPI package.

**Comment by micahcochran** [comment]
I'm a little rusty on my python, please keep that in in mind with my advice.

Hard coded paths are great for fallback.  Something that is a little more robust is to add a setup.py and allow the user to set an environment variable during installation, say QGIS_PATH.  The setup.py should NOT install if no QGIS python environment is found and should give the user an appropriate error message.

[pyproj](https://github.com/jswhit/pyproj) does this in its [setup.py](https://github.com/jswhit/pyproj/blob/master/setup.py).  If PROJ.4 library is already installed on the system, it writes the path into the datadir.py, as a variable.  The __init__.py imports the value from datadir.py.

I hope that is the kind of feedback that you were looking for.

**Comment by mcvittal** [comment]
It's an OK solution, and one I considered at first, but if the user upgrades their version of QGIS, I'd need to have some way of notifying qpy that this has changed. A possible solution would be to use `os.path.isdir` to check if QGIS is installed in the OSGeo4W folder. If it's not in there, it can then check if the word QGIS is in any folder within Program Files or Program Files (x86), and then append the path to the processing python modules. 

I'll test it when I have access to a windows dev machine on Monday, but I think that it's the best and only way to make this work even when QGIS updates to a newer version.

**Comment by micahcochran** [comment]
Good point.
This could also be done with runtime environment variables.  OSGeo4W has a batchfile that sets up the environment, C:\OSGeo4W\OSGeo4W.bat  

You'd set that environment variable up and it is done.  This does require some manual editing, but I think it would work fine for OSGeo4W.  It would not work so well for other Windows installations.

Searching the path sounds a a bit ugly for qpy to have to do every time.

**Comment by mcvittal** [comment]
Good news! The search method works perfectly and impacts module load time minimally (If your computer is having a hard time searching through a few folder names, its definitely not suited for GIS analysis). However, I broke something in processing_obj.py (I think) rendering it unable to load any layers. I've been meaning to re-write processing_obj anyways, since it's a bit messy and written through trial and error.

**Comment by mcvittal** [comment]
After a solid 2 years of stagnation and not touching this project, development is back and well underway! Thank you for your contributions in this thread. 

I'm closing this issue as it pertains to the old, buggy, not very well laid out version of qpy. A new version (qpy3) is in the works that is now tested to work great with both Linux and Windows (provided it is run through the osgeo4w shell). 

Listing of all algorithms works great, and a test run of an algorithm in Linux and Windows yields results. 

As for naming, we're going to go with `qpy3` as its intuitive and doesn't seem to be taken on PyPI. Just have to create the proper packaging to upload it, but I'll get around to that soon.
